### PR TITLE
Fix spec

### PR DESCRIPTION
**Pull request by andela-sdamian**
Used the helper module were necessary and refactored test, allowing it to use less instance variable - using attr_reader as an alternative.

### CODE REVIEW

**Comment by 0duaht** [comment]
Sweet! Great stuff! Noticed you didn't finish replacing `stub_flutterwave` method in some test classes with the one from the helper. Any reasons to that? @andela-sdamian

**Comment by andela-sdamian** [comment]
Hey @0duaht I think, I skipped it unknowingly. Fixed now.

**Comment by 0duaht** [comment]
Hey @andela-sdamian, so, it's still duplicated in `pay_test`, `account_test` and `ach_test`. Once those are fixed, I'll merge in.

**Comment by andela-sdamian** [comment]
Hey, @0duaht thanks for pointing that out. Done now.

**Comment by 0duaht** [comment]
Nice! All good now. Thanks @andela-sdamian

**Pull request merged**
